### PR TITLE
parameterize stage

### PR DESCRIPTION
**Pull request by dholth**

### CODE REVIEW

**Comment by msarahan** [comment]
All of this work on conda index is really awesome to see. You've made huge improvements. Thanks for your work here.

**Comment by dholth** [comment]
@msarahan let me know if you get a chance to run the code

**Comment by dholth** [comment]
replaced with other PR

**Comment by msarahan** [comment]
I don't have anything relevant to run it on (just a lowly once-in-a-while conda user now), but I'm betting that it vastly improves the indexing time for the conda-forge mirroring process.

**Comment by dholth** [comment]
Yes, I suspect that no one else has the index conda-forge problem

**Pull request closed without merging**
